### ISSUE TITLE
[sks] Error "cp: can't create 'PTree/': Is a directory" in sks-init with no dump

### ISSUE THREAD

**Issue by MatthiasLohr** [zhsj/dockerfile#4]
Hello,

for testing reasons I tried to run sks-init without any available dump, that means my `/var/lib/sks` directory is empty. I always get this error:
`
cp: can't create 'PTree/': Is a directory
`

Way to reproduce:
`docker run --rm -v $(pwd)/sks:/var/lib/sks zhusj/sks sks-init` or simply `docker run --rm zhusj/sks sks-init`.

Best regards
Matthias

**Comment by zhsj** [comment]
The image [autobuild](https://hub.docker.com/r/zhusj/sks/builds/) has finished. Please try again.
