### ISSUE TITLE
Add information to readme about original GitHub project

### ISSUE THREAD

**Issue by mr-yaky** [zhsj/dockerfile#5]
Hi, can you please add information about original my project after forking it? We will support our Redmine docker image in the future and 4.0.x version will be added as additional docker tag as well.

I just found your project and information that it’s  a fork from our repo in google.

Best Regard,

Vitaly

**Comment by zhsj** [comment]
Sorry for the late reply, and thanks for contact. I've added it in README.md

**Comment by mr-yaky** [comment]
Thank you!
